repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: pipenv run python -m unittest discover -s tests
        language: system
        always_run: true
        pass_filenames: false
